Cufon.replace('.header_inner h2');
Cufon.replace('.header_inner h3');
Cufon.replace('.header_inner h1#head');
Cufon.replace('.header_inner span.tag_line');
Cufon.replace('#inner_container .head_content');
Cufon.replace('nav#footer_bot .invoicera_sec h4');
Cufon.replace('nav#footer_bot .others h4');
Cufon.replace('#inner_container .latest_news h3');
Cufon.replace('#inner_container .features ul li h3 a');
Cufon.replace('.features_sec h3 a');
Cufon.replace('.pricing_box .price span');
Cufon.replace('.pricing_box_outer .col1 h2');
Cufon.replace('.pricing_box .price div.dollar, .pricing_box .price div.per_month, .pricing_box .price div.price_inner p');
Cufon.replace('.content_bot .text');
Cufon.replace('.content_bot .faq h3');
Cufon.replace('#banner_pricing .five_reason_sec h3');
Cufon.replace('#services .head');
Cufon.replace('#services .content .content_inner h3');
Cufon.replace('#custom_developement .top_sec .head');
Cufon.replace('#custom_developement .mid_box .left_sec h3');
Cufon.replace('#custom_developement h3.big_head');
Cufon.replace('#custom_developement .faq h3');
Cufon.replace('#featured .feature_content h3');
Cufon.replace('#data_back h3');
Cufon.replace('#left_addon h3');
Cufon.replace('aside#right_addons h3');
Cufon.replace('.addon_inner_sec .top_sec .inner_top h3');
Cufon.replace('.left_about article.left_abt_inner .head h3');
Cufon.replace('aside.right_about .top_about p');
Cufon.replace('aside.right_small_container a.btn span');
Cufon.replace('aside#sidebar h3');
Cufon.replace('aside.sidebar h3');
Cufon.replace('aside#right_contact h3');
Cufon.replace('nav#main ul li a span', {hover: true,hoverables: { a: true, span: true }});
Cufon.replace('nav#main ul li a:hover');
Cufon.replace('nav#main ul li a:hover span');
Cufon.replace('nav#main ul li.drop ul li a', {hover: true,hoverables: { a: true, span: true }});
Cufon.replace('aside#right_api h3');
Cufon.replace('.latest_tweets h4');
Cufon.replace('#cust_template h3');
Cufon.replace('.features_sec h3.full_width');
Cufon.replace('h2.cat_title');
Cufon.replace('aside#sidebar h3');
Cufon.replace('#tour_sec ul li h3');
Cufon.replace('#tour_sec ul li h5');
Cufon.replace('.main_dis p');
Cufon.replace('#inner_container .featured_in h3');


//Cufon.replace('#sub1'); // Requires a selector engine for IE 6-7, see above
